#get all books
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json 


###

//create a book
POST http://localhost:3001 HTTP/1.1
Content-Type: application/json

{
    "title": "Harry Potter"
}


# update a book
###
PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "zahoor shinwari"
}

# delete a books
###
DELETE http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json